### ISSUE TITLE
Add possibility to use docker labels for folder

### ISSUE THREAD

**Issue by MissingDLL** [scolcipitato/folder.view#4]
When managing docker-containers from within a docker-compose file it would be awesome to define a docker-folder via lables.

**Comment by scolcipitato** [comment]
This feature is already present in the plugin, I forgot to add it to the main post, I added it now.
You can add the label `folder.view`, the value should be the name of the folder.

**Comment by MissingDLL** [comment]
Thanks. Where did you put it? I tested it and it worked, when the folder already exsists. Would it be possibile to create that folder if not Present?

**Comment by scolcipitato** [comment]
If you use the compose manager plugin you can ask the creator of that plugin for integration with my plugin, if you use compose from cli what you ask is not possible, the way the plugin works is different and I won't change it for keeping the code similar to the code for the VM.
Anyway creating a folder before changing the compose file is simple enough.
I suggest to ask for features in the support thread on the unRAID forum and not here as I tend to be more active there rather than here.
